export interface EmojiDef {
  emoji: string;
  label: string;
}

export const EMOJI_CATEGORIES: readonly string[] = [
  'Smileys',
  'People',
  'Nature',
  'Food',
  'Travel',
  'Activities',
  'Objects',
  'Symbols',
] as const;

export const EMOJIS_BY_CATEGORY: Record<string, EmojiDef[]> = {
  Smileys: [
    { emoji: '😀', label: 'Grinning' },
    { emoji: '😃', label: 'Big Smile' },
    { emoji: '😄', label: 'Smile' },
    { emoji: '😁', label: 'Beaming' },
    { emoji: '😆', label: 'Laughing' },
    { emoji: '😅', label: 'Sweat Smile' },
    { emoji: '🤣', label: 'Rolling' },
    { emoji: '😂', label: 'Joy' },
    { emoji: '🙂', label: 'Slightly Smiling' },
    { emoji: '🙃', label: 'Upside Down' },
    { emoji: '😉', label: 'Winking' },
    { emoji: '😊', label: 'Blushing' },
    { emoji: '😇', label: 'Halo' },
    { emoji: '🥰', label: 'Hearts' },
    { emoji: '😍', label: 'Heart Eyes' },
    { emoji: '🤩', label: 'Star Struck' },
    { emoji: '😘', label: 'Kissing Heart' },
    { emoji: '😗', label: 'Kissing' },
    { emoji: '😚', label: 'Kissing Closed' },
    { emoji: '😙', label: 'Kissing Smiling' },
    { emoji: '🥲', label: 'Holding Back' },
    { emoji: '😋', label: 'Yum' },
    { emoji: '😛', label: 'Tongue' },
    { emoji: '😜', label: 'Winking Tongue' },
    { emoji: '🤪', label: 'Zany' },
    { emoji: '😝', label: 'Squinting Tongue' },
    { emoji: '🤑', label: 'Money Mouth' },
    { emoji: '🤗', label: 'Hugging' },
    { emoji: '🤭', label: 'Hand Over Mouth' },
    { emoji: '🤫', label: 'Shushing' },
    { emoji: '🤔', label: 'Thinking' },
    { emoji: '🤐', label: 'Zipper Mouth' },
    { emoji: '🤨', label: 'Raised Eyebrow' },
    { emoji: '😐', label: 'Neutral' },
    { emoji: '😑', label: 'Expressionless' },
    { emoji: '😶', label: 'No Mouth' },
    { emoji: '😏', label: 'Smirking' },
    { emoji: '😒', label: 'Unamused' },
    { emoji: '🙄', label: 'Eye Roll' },
    { emoji: '😬', label: 'Grimacing' },
    { emoji: '😮', label: 'Open Mouth' },
    { emoji: '😯', label: 'Hushed' },
    { emoji: '😲', label: 'Astonished' },
    { emoji: '😳', label: 'Flushed' },
    { emoji: '🥺', label: 'Pleading' },
    { emoji: '😦', label: 'Frowning' },
    { emoji: '😧', label: 'Anguished' },
    { emoji: '😨', label: 'Fearful' },
    { emoji: '😰', label: 'Anxious' },
    { emoji: '😥', label: 'Sad Relief' },
    { emoji: '😢', label: 'Crying' },
    { emoji: '😭', label: 'Loudly Crying' },
    { emoji: '😱', label: 'Screaming' },
    { emoji: '😖', label: 'Confounded' },
    { emoji: '😣', label: 'Persevering' },
    { emoji: '😞', label: 'Disappointed' },
    { emoji: '😓', label: 'Downcast Sweat' },
    { emoji: '😩', label: 'Weary' },
    { emoji: '😫', label: 'Tired' },
    { emoji: '🥱', label: 'Yawning' },
    { emoji: '😤', label: 'Triumph' },
    { emoji: '😡', label: 'Pouting' },
    { emoji: '😠', label: 'Angry' },
    { emoji: '🤬', label: 'Cursing' },
    { emoji: '😈', label: 'Smiling Devil' },
    { emoji: '👿', label: 'Angry Devil' },
    { emoji: '💀', label: 'Skull' },
    { emoji: '☠️', label: 'Skull Crossbones' },
    { emoji: '💩', label: 'Poop' },
    { emoji: '🤡', label: 'Clown' },
    { emoji: '👹', label: 'Ogre' },
    { emoji: '👺', label: 'Goblin' },
    { emoji: '👻', label: 'Ghost' },
    { emoji: '👽', label: 'Alien' },
    { emoji: '🤖', label: 'Robot' },
    { emoji: '😺', label: 'Cat Grin' },
    { emoji: '😸', label: 'Cat Joy' },
    { emoji: '😹', label: 'Cat Tears' },
    { emoji: '😻', label: 'Cat Hearts' },
    { emoji: '😼', label: 'Cat Smirk' },
    { emoji: '😽', label: 'Cat Kiss' },
    { emoji: '🙀', label: 'Cat Scream' },
    { emoji: '😿', label: 'Cat Cry' },
    { emoji: '😾', label: 'Cat Pout' },
  ],

  People: [
    { emoji: '👋', label: 'Waving Hand' },
    { emoji: '🤚', label: 'Raised Back Hand' },
    { emoji: '🖐️', label: 'Hand Fingers Open' },
    { emoji: '✋', label: 'Raised Hand' },
    { emoji: '🖖', label: 'Vulcan Salute' },
    { emoji: '👌', label: 'OK Hand' },
    { emoji: '🤌', label: 'Pinched Fingers' },
    { emoji: '✌️', label: 'Victory' },
    { emoji: '🤞', label: 'Crossed Fingers' },
    { emoji: '🤟', label: 'Love You' },
    { emoji: '🤘', label: 'Sign of Horns' },
    { emoji: '🤙', label: 'Call Me' },
    { emoji: '👈', label: 'Pointing Left' },
    { emoji: '👉', label: 'Pointing Right' },
    { emoji: '👆', label: 'Pointing Up' },
    { emoji: '🖕', label: 'Middle Finger' },
    { emoji: '👇', label: 'Pointing Down' },
    { emoji: '☝️', label: 'Index Up' },
    { emoji: '👍', label: 'Thumbs Up' },
    { emoji: '👎', label: 'Thumbs Down' },
    { emoji: '✊', label: 'Raised Fist' },
    { emoji: '👊', label: 'Oncoming Fist' },
    { emoji: '🤛', label: 'Left Fist' },
    { emoji: '🤜', label: 'Right Fist' },
    { emoji: '👏', label: 'Clapping' },
    { emoji: '🙌', label: 'Raising Hands' },
    { emoji: '👐', label: 'Open Hands' },
    { emoji: '🤲', label: 'Palms Up' },
    { emoji: '🤝', label: 'Handshake' },
    { emoji: '🙏', label: 'Folded Hands' },
    { emoji: '✍️', label: 'Writing' },
    { emoji: '💅', label: 'Nail Polish' },
    { emoji: '🤳', label: 'Selfie' },
    { emoji: '💪', label: 'Muscle' },
    { emoji: '🦾', label: 'Mechanical Arm' },
    { emoji: '🦿', label: 'Mechanical Leg' },
    { emoji: '🦵', label: 'Leg' },
    { emoji: '🦶', label: 'Foot' },
    { emoji: '👂', label: 'Ear' },
    { emoji: '🦻', label: 'Ear Hearing Aid' },
    { emoji: '👃', label: 'Nose' },
    { emoji: '🧠', label: 'Brain' },
    { emoji: '🫀', label: 'Heart Organ' },
    { emoji: '🫁', label: 'Lungs' },
    { emoji: '🦷', label: 'Tooth' },
    { emoji: '🦴', label: 'Bone' },
    { emoji: '👀', label: 'Eyes' },
    { emoji: '👁️', label: 'Eye' },
    { emoji: '👅', label: 'Tongue' },
    { emoji: '👄', label: 'Lips' },
    { emoji: '🫦', label: 'Biting Lip' },
    { emoji: '👶', label: 'Baby' },
    { emoji: '🧒', label: 'Child' },
    { emoji: '👦', label: 'Boy' },
    { emoji: '👧', label: 'Girl' },
    { emoji: '🧑', label: 'Person' },
    { emoji: '👱', label: 'Blond Person' },
    { emoji: '👨', label: 'Man' },
    { emoji: '🧔', label: 'Bearded Person' },
    { emoji: '👩', label: 'Woman' },
    { emoji: '🧓', label: 'Older Person' },
    { emoji: '👴', label: 'Old Man' },
    { emoji: '👵', label: 'Old Woman' },
    { emoji: '🙍', label: 'Frowning Person' },
    { emoji: '🙎', label: 'Pouting Person' },
    { emoji: '🙅', label: 'No Gesture' },
    { emoji: '🙆', label: 'OK Gesture' },
    { emoji: '💁', label: 'Tipping Hand' },
    { emoji: '🙋', label: 'Raising Hand' },
    { emoji: '🧏', label: 'Deaf Person' },
    { emoji: '🙇', label: 'Bowing' },
    { emoji: '🤦', label: 'Facepalm' },
    { emoji: '🤷', label: 'Shrug' },
    { emoji: '🧑‍💻', label: 'Technologist' },
    { emoji: '🧑‍🎨', label: 'Artist' },
    { emoji: '🧑‍🏫', label: 'Teacher' },
    { emoji: '🧑‍🍳', label: 'Cook' },
    { emoji: '🧑‍🔬', label: 'Scientist' },
    { emoji: '🧑‍💼', label: 'Office Worker' },
  ],

  Nature: [
    { emoji: '🐶', label: 'Dog' },
    { emoji: '🐱', label: 'Cat' },
    { emoji: '🐭', label: 'Mouse' },
    { emoji: '🐹', label: 'Hamster' },
    { emoji: '🐰', label: 'Rabbit' },
    { emoji: '🦊', label: 'Fox' },
    { emoji: '🐻', label: 'Bear' },
    { emoji: '🐼', label: 'Panda' },
    { emoji: '🐨', label: 'Koala' },
    { emoji: '🐯', label: 'Tiger' },
    { emoji: '🦁', label: 'Lion' },
    { emoji: '🐮', label: 'Cow' },
    { emoji: '🐷', label: 'Pig' },
    { emoji: '🐸', label: 'Frog' },
    { emoji: '🐵', label: 'Monkey' },
    { emoji: '🙈', label: 'See-No-Evil' },
    { emoji: '🙉', label: 'Hear-No-Evil' },
    { emoji: '🙊', label: 'Speak-No-Evil' },
    { emoji: '🐔', label: 'Chicken' },
    { emoji: '🐧', label: 'Penguin' },
    { emoji: '🐦', label: 'Bird' },
    { emoji: '🐤', label: 'Chick' },
    { emoji: '🦆', label: 'Duck' },
    { emoji: '🦅', label: 'Eagle' },
    { emoji: '🦉', label: 'Owl' },
    { emoji: '🦇', label: 'Bat' },
    { emoji: '🐝', label: 'Bee' },
    { emoji: '🐛', label: 'Bug' },
    { emoji: '🦋', label: 'Butterfly' },
    { emoji: '🐌', label: 'Snail' },
    { emoji: '🐞', label: 'Ladybug' },
    { emoji: '🐜', label: 'Ant' },
    { emoji: '🦟', label: 'Mosquito' },
    { emoji: '🦗', label: 'Cricket' },
    { emoji: '🐢', label: 'Turtle' },
    { emoji: '🐍', label: 'Snake' },
    { emoji: '🦎', label: 'Lizard' },
    { emoji: '🦕', label: 'Sauropod' },
    { emoji: '🦖', label: 'T-Rex' },
    { emoji: '🐙', label: 'Octopus' },
    { emoji: '🦑', label: 'Squid' },
    { emoji: '🦐', label: 'Shrimp' },
    { emoji: '🦞', label: 'Lobster' },
    { emoji: '🦀', label: 'Crab' },
    { emoji: '🐡', label: 'Blowfish' },
    { emoji: '🐠', label: 'Tropical Fish' },
    { emoji: '🐟', label: 'Fish' },
    { emoji: '🐬', label: 'Dolphin' },
    { emoji: '🐳', label: 'Whale' },
    { emoji: '🐋', label: 'Whale 2' },
    { emoji: '🦈', label: 'Shark' },
    { emoji: '🐊', label: 'Crocodile' },
    { emoji: '🦓', label: 'Zebra' },
    { emoji: '🦍', label: 'Gorilla' },
    { emoji: '🦧', label: 'Orangutan' },
    { emoji: '🦣', label: 'Mammoth' },
    { emoji: '🐘', label: 'Elephant' },
    { emoji: '🦛', label: 'Hippo' },
    { emoji: '🦏', label: 'Rhino' },
    { emoji: '🐪', label: 'Dromedary' },
    { emoji: '🐫', label: 'Camel' },
    { emoji: '🦒', label: 'Giraffe' },
    { emoji: '🦘', label: 'Kangaroo' },
    { emoji: '🦬', label: 'Bison' },
    { emoji: '🐃', label: 'Water Buffalo' },
    { emoji: '🐂', label: 'Ox' },
    { emoji: '🐄', label: 'Cow 2' },
    { emoji: '🐎', label: 'Horse' },
    { emoji: '🐖', label: 'Pig 2' },
    { emoji: '🐏', label: 'Ram' },
    { emoji: '🐑', label: 'Ewe' },
    { emoji: '🦙', label: 'Llama' },
    { emoji: '🐐', label: 'Goat' },
    { emoji: '🦌', label: 'Deer' },
    { emoji: '🐕', label: 'Dog 2' },
    { emoji: '🦮', label: 'Guide Dog' },
    { emoji: '🐩', label: 'Poodle' },
    { emoji: '🐈', label: 'Cat 2' },
    { emoji: '🐓', label: 'Rooster' },
    { emoji: '🦃', label: 'Turkey' },
    { emoji: '🦚', label: 'Peacock' },
    { emoji: '🦜', label: 'Parrot' },
    { emoji: '🌸', label: 'Cherry Blossom' },
    { emoji: '💐', label: 'Bouquet' },
    { emoji: '🌹', label: 'Rose' },
    { emoji: '🥀', label: 'Wilted Flower' },
    { emoji: '🌺', label: 'Hibiscus' },
    { emoji: '🌻', label: 'Sunflower' },
    { emoji: '🌼', label: 'Blossom' },
    { emoji: '🌷', label: 'Tulip' },
    { emoji: '🌱', label: 'Seedling' },
    { emoji: '🌲', label: 'Tree' },
    { emoji: '🌳', label: 'Deciduous' },
    { emoji: '🌴', label: 'Palm Tree' },
    { emoji: '🌵', label: 'Cactus' },
    { emoji: '🍀', label: 'Four Leaf Clover' },
    { emoji: '🍃', label: 'Leaves' },
    { emoji: '🌊', label: 'Wave' },
    { emoji: '🌋', label: 'Volcano' },
    { emoji: '⛰️', label: 'Mountain' },
    { emoji: '🏔️', label: 'Snow Mountain' },
    { emoji: '🌅', label: 'Sunrise' },
    { emoji: '🌄', label: 'Sunrise Mountains' },
    { emoji: '🌠', label: 'Shooting Star' },
    { emoji: '🌌', label: 'Milky Way' },
    { emoji: '⭐', label: 'Star' },
    { emoji: '🌟', label: 'Glowing Star' },
    { emoji: '✨', label: 'Sparkles' },
    { emoji: '⚡', label: 'Lightning' },
    { emoji: '❄️', label: 'Snowflake' },
    { emoji: '🌈', label: 'Rainbow' },
    { emoji: '☀️', label: 'Sun' },
    { emoji: '🌙', label: 'Moon' },
    { emoji: '🌤️', label: 'Sun Behind Cloud' },
    { emoji: '⛅', label: 'Partly Cloudy' },
    { emoji: '🌦️', label: 'Rain' },
    { emoji: '🌧️', label: 'Cloud Rain' },
    { emoji: '⛈️', label: 'Thunderstorm' },
    { emoji: '🌩️', label: 'Lightning Cloud' },
    { emoji: '🌨️', label: 'Snow Cloud' },
    { emoji: '🌪️', label: 'Tornado' },
    { emoji: '🌫️', label: 'Fog' },
    { emoji: '🌬️', label: 'Wind' },
    { emoji: '🌀', label: 'Cyclone' },
  ],

  Food: [
    { emoji: '🍎', label: 'Red Apple' },
    { emoji: '🍊', label: 'Tangerine' },
    { emoji: '🍋', label: 'Lemon' },
    { emoji: '🍌', label: 'Banana' },
    { emoji: '🍉', label: 'Watermelon' },
    { emoji: '🍇', label: 'Grapes' },
    { emoji: '🍓', label: 'Strawberry' },
    { emoji: '🫐', label: 'Blueberries' },
    { emoji: '🍈', label: 'Melon' },
    { emoji: '🍒', label: 'Cherries' },
    { emoji: '🍑', label: 'Peach' },
    { emoji: '🥭', label: 'Mango' },
    { emoji: '🍍', label: 'Pineapple' },
    { emoji: '🥥', label: 'Coconut' },
    { emoji: '🥝', label: 'Kiwi' },
    { emoji: '🍅', label: 'Tomato' },
    { emoji: '🫒', label: 'Olive' },
    { emoji: '🥑', label: 'Avocado' },
    { emoji: '🍆', label: 'Eggplant' },
    { emoji: '🥕', label: 'Carrot' },
    { emoji: '🌽', label: 'Corn' },
    { emoji: '🌶️', label: 'Chili' },
    { emoji: '🥒', label: 'Cucumber' },
    { emoji: '🥬', label: 'Leafy Green' },
    { emoji: '🥦', label: 'Broccoli' },
    { emoji: '🧄', label: 'Garlic' },
    { emoji: '🧅', label: 'Onion' },
    { emoji: '🍄', label: 'Mushroom' },
    { emoji: '🥜', label: 'Peanuts' },
    { emoji: '🌰', label: 'Chestnut' },
    { emoji: '🍞', label: 'Bread' },
    { emoji: '🥐', label: 'Croissant' },
    { emoji: '🥖', label: 'Baguette' },
    { emoji: '🫓', label: 'Flatbread' },
    { emoji: '🥨', label: 'Pretzel' },
    { emoji: '🥯', label: 'Bagel' },
    { emoji: '🧀', label: 'Cheese' },
    { emoji: '🍳', label: 'Fried Egg' },
    { emoji: '🍔', label: 'Hamburger' },
    { emoji: '🍟', label: 'Fries' },
    { emoji: '🍕', label: 'Pizza' },
    { emoji: '🌭', label: 'Hot Dog' },
    { emoji: '🥪', label: 'Sandwich' },
    { emoji: '🌮', label: 'Taco' },
    { emoji: '🌯', label: 'Burrito' },
    { emoji: '🫔', label: 'Tamale' },
    { emoji: '🥙', label: 'Pita' },
    { emoji: '🧆', label: 'Falafel' },
    { emoji: '🥚', label: 'Egg' },
    { emoji: '🍿', label: 'Popcorn' },
    { emoji: '🧂', label: 'Salt' },
    { emoji: '🥓', label: 'Bacon' },
    { emoji: '🥩', label: 'Steak' },
    { emoji: '🍗', label: 'Chicken Leg' },
    { emoji: '🍖', label: 'Meat on Bone' },
    { emoji: '🌮', label: 'Taco' },
    { emoji: '🍜', label: 'Ramen' },
    { emoji: '🍝', label: 'Spaghetti' },
    { emoji: '🍛', label: 'Curry' },
    { emoji: '🍣', label: 'Sushi' },
    { emoji: '🍱', label: 'Bento Box' },
    { emoji: '🍦', label: 'Ice Cream' },
    { emoji: '🍧', label: 'Shaved Ice' },
    { emoji: '🍨', label: 'Ice Cream Bowl' },
    { emoji: '🍩', label: 'Donut' },
    { emoji: '🍪', label: 'Cookie' },
    { emoji: '🎂', label: 'Birthday Cake' },
    { emoji: '🍰', label: 'Shortcake' },
    { emoji: '🧁', label: 'Cupcake' },
    { emoji: '🥧', label: 'Pie' },
    { emoji: '🍫', label: 'Chocolate' },
    { emoji: '🍬', label: 'Candy' },
    { emoji: '🍭', label: 'Lollipop' },
    { emoji: '🫖', label: 'Teapot' },
    { emoji: '☕', label: 'Coffee' },
    { emoji: '🧋', label: 'Bubble Tea' },
    { emoji: '🍵', label: 'Tea' },
    { emoji: '🍺', label: 'Beer' },
    { emoji: '🍻', label: 'Beers' },
    { emoji: '🥂', label: 'Champagne' },
    { emoji: '🍷', label: 'Wine' },
    { emoji: '🍸', label: 'Cocktail' },
    { emoji: '🍹', label: 'Tropical Drink' },
    { emoji: '🧃', label: 'Juice Box' },
    { emoji: '🥤', label: 'Cup with Straw' },
    { emoji: '🧊', label: 'Ice' },
  ],

  Travel: [
    { emoji: '🚗', label: 'Car' },
    { emoji: '🚕', label: 'Taxi' },
    { emoji: '🚙', label: 'SUV' },
    { emoji: '🚌', label: 'Bus' },
    { emoji: '🚎', label: 'Trolleybus' },
    { emoji: '🏎️', label: 'Racing Car' },
    { emoji: '🚓', label: 'Police Car' },
    { emoji: '🚑', label: 'Ambulance' },
    { emoji: '🚒', label: 'Fire Engine' },
    { emoji: '🚐', label: 'Minibus' },
    { emoji: '🛻', label: 'Pickup Truck' },
    { emoji: '🚚', label: 'Delivery Truck' },
    { emoji: '🚛', label: 'Articulated Lorry' },
    { emoji: '🚜', label: 'Tractor' },
    { emoji: '🏍️', label: 'Motorcycle' },
    { emoji: '🛵', label: 'Motor Scooter' },
    { emoji: '🚲', label: 'Bicycle' },
    { emoji: '🛴', label: 'Kick Scooter' },
    { emoji: '🛹', label: 'Skateboard' },
    { emoji: '🚁', label: 'Helicopter' },
    { emoji: '✈️', label: 'Airplane' },
    { emoji: '🛩️', label: 'Small Airplane' },
    { emoji: '🚀', label: 'Rocket' },
    { emoji: '🛸', label: 'UFO' },
    { emoji: '🚂', label: 'Train' },
    { emoji: '🚃', label: 'Train Car' },
    { emoji: '🚄', label: 'Bullet Train' },
    { emoji: '🚅', label: 'High-Speed Train' },
    { emoji: '🚆', label: 'Train 2' },
    { emoji: '🚇', label: 'Metro' },
    { emoji: '🚈', label: 'Light Rail' },
    { emoji: '🚉', label: 'Station' },
    { emoji: '🚊', label: 'Tram' },
    { emoji: '🚞', label: 'Mountain Railway' },
    { emoji: '⛵', label: 'Sailboat' },
    { emoji: '🛶', label: 'Canoe' },
    { emoji: '🚤', label: 'Speedboat' },
    { emoji: '⛴️', label: 'Ferry' },
    { emoji: '🛳️', label: 'Passenger Ship' },
    { emoji: '🚢', label: 'Ship' },
    { emoji: '🏖️', label: 'Beach' },
    { emoji: '🏝️', label: 'Desert Island' },
    { emoji: '⛺', label: 'Tent' },
    { emoji: '🏕️', label: 'Camping' },
    { emoji: '🗺️', label: 'World Map' },
    { emoji: '🧭', label: 'Compass' },
    { emoji: '🗼', label: 'Tokyo Tower' },
    { emoji: '🗽', label: 'Statue of Liberty' },
    { emoji: '🗿', label: 'Moai' },
    { emoji: '🏰', label: 'Castle' },
    { emoji: '🏯', label: 'Japanese Castle' },
    { emoji: '🕌', label: 'Mosque' },
    { emoji: '🛕', label: 'Hindu Temple' },
    { emoji: '⛪', label: 'Church' },
    { emoji: '🕍', label: 'Synagogue' },
    { emoji: '🌍', label: 'Globe Europe' },
    { emoji: '🌎', label: 'Globe Americas' },
    { emoji: '🌏', label: 'Globe Asia' },
  ],

  Activities: [
    { emoji: '⚽', label: 'Soccer' },
    { emoji: '🏀', label: 'Basketball' },
    { emoji: '🏈', label: 'Football' },
    { emoji: '⚾', label: 'Baseball' },
    { emoji: '🥎', label: 'Softball' },
    { emoji: '🎾', label: 'Tennis' },
    { emoji: '🏐', label: 'Volleyball' },
    { emoji: '🏉', label: 'Rugby' },
    { emoji: '🥏', label: 'Flying Disc' },
    { emoji: '🎱', label: 'Billiards' },
    { emoji: '🏓', label: 'Ping Pong' },
    { emoji: '🏸', label: 'Badminton' },
    { emoji: '🥅', label: 'Goal Net' },
    { emoji: '🏒', label: 'Ice Hockey' },
    { emoji: '🏑', label: 'Field Hockey' },
    { emoji: '🏏', label: 'Cricket' },
    { emoji: '🥍', label: 'Lacrosse' },
    { emoji: '🏹', label: 'Bow and Arrow' },
    { emoji: '⛳', label: 'Golf' },
    { emoji: '🤿', label: 'Diving Mask' },
    { emoji: '🎣', label: 'Fishing' },
    { emoji: '🎿', label: 'Skis' },
    { emoji: '🛷', label: 'Sled' },
    { emoji: '🥌', label: 'Curling Stone' },
    { emoji: '🎯', label: 'Bullseye' },
    { emoji: '🎳', label: 'Bowling' },
    { emoji: '🏋️', label: 'Weightlifting' },
    { emoji: '🤼', label: 'Wrestling' },
    { emoji: '🤸', label: 'Gymnastics' },
    { emoji: '🤺', label: 'Fencing' },
    { emoji: '🏇', label: 'Horse Racing' },
    { emoji: '⛷️', label: 'Skier' },
    { emoji: '🏂', label: 'Snowboarder' },
    { emoji: '🏄', label: 'Surfing' },
    { emoji: '🚣', label: 'Rowing' },
    { emoji: '🧗', label: 'Climbing' },
    { emoji: '🚵', label: 'Mountain Biking' },
    { emoji: '🚴', label: 'Cycling' },
    { emoji: '🏆', label: 'Trophy' },
    { emoji: '🥇', label: 'Gold Medal' },
    { emoji: '🥈', label: 'Silver Medal' },
    { emoji: '🥉', label: 'Bronze Medal' },
    { emoji: '🎖️', label: 'Medal' },
    { emoji: '🏅', label: 'Sports Medal' },
    { emoji: '🎗️', label: 'Reminder Ribbon' },
    { emoji: '🎪', label: 'Circus Tent' },
    { emoji: '🎭', label: 'Performing Arts' },
    { emoji: '🎨', label: 'Artist Palette' },
    { emoji: '🎬', label: 'Clapper Board' },
    { emoji: '🎤', label: 'Microphone' },
    { emoji: '🎧', label: 'Headphones' },
    { emoji: '🎼', label: 'Musical Score' },
    { emoji: '🎵', label: 'Note' },
    { emoji: '🎶', label: 'Notes' },
    { emoji: '🎷', label: 'Saxophone' },
    { emoji: '🎸', label: 'Guitar' },
    { emoji: '🎹', label: 'Piano' },
    { emoji: '🎺', label: 'Trumpet' },
    { emoji: '🎻', label: 'Violin' },
    { emoji: '🥁', label: 'Drum' },
    { emoji: '🪘', label: 'Long Drum' },
    { emoji: '🎲', label: 'Die' },
    { emoji: '♟️', label: 'Chess Pawn' },
    { emoji: '🎮', label: 'Video Game' },
    { emoji: '🕹️', label: 'Joystick' },
    { emoji: '🎰', label: 'Slot Machine' },
    { emoji: '🎴', label: 'Flower Cards' },
    { emoji: '🀄', label: 'Mahjong' },
  ],

  Objects: [
    { emoji: '💡', label: 'Light Bulb' },
    { emoji: '🔦', label: 'Flashlight' },
    { emoji: '🕯️', label: 'Candle' },
    { emoji: '🔋', label: 'Battery' },
    { emoji: '💻', label: 'Laptop' },
    { emoji: '🖥️', label: 'Desktop' },
    { emoji: '🖨️', label: 'Printer' },
    { emoji: '⌨️', label: 'Keyboard' },
    { emoji: '🖱️', label: 'Mouse' },
    { emoji: '📱', label: 'Phone' },
    { emoji: '📲', label: 'Phone Arrow' },
    { emoji: '☎️', label: 'Telephone' },
    { emoji: '📞', label: 'Phone Receiver' },
    { emoji: '📟', label: 'Pager' },
    { emoji: '📠', label: 'Fax' },
    { emoji: '📷', label: 'Camera' },
    { emoji: '📸', label: 'Camera Flash' },
    { emoji: '📹', label: 'Video Camera' },
    { emoji: '📺', label: 'TV' },
    { emoji: '📻', label: 'Radio' },
    { emoji: '🎙️', label: 'Studio Mic' },
    { emoji: '⏰', label: 'Alarm Clock' },
    { emoji: '🕰️', label: 'Mantelpiece Clock' },
    { emoji: '⌚', label: 'Watch' },
    { emoji: '📡', label: 'Satellite' },
    { emoji: '🔭', label: 'Telescope' },
    { emoji: '🔬', label: 'Microscope' },
    { emoji: '💊', label: 'Pill' },
    { emoji: '🩺', label: 'Stethoscope' },
    { emoji: '🩻', label: 'X-Ray' },
    { emoji: '🧬', label: 'DNA' },
    { emoji: '🔑', label: 'Key' },
    { emoji: '🗝️', label: 'Old Key' },
    { emoji: '🔐', label: 'Locked with Key' },
    { emoji: '🔒', label: 'Locked' },
    { emoji: '🔓', label: 'Unlocked' },
    { emoji: '🪪', label: 'ID Card' },
    { emoji: '📝', label: 'Memo' },
    { emoji: '✏️', label: 'Pencil' },
    { emoji: '📌', label: 'Pushpin' },
    { emoji: '📍', label: 'Round Pushpin' },
    { emoji: '📎', label: 'Paperclip' },
    { emoji: '🖇️', label: 'Paperclips' },
    { emoji: '📏', label: 'Ruler' },
    { emoji: '📐', label: 'Triangular Ruler' },
    { emoji: '✂️', label: 'Scissors' },
    { emoji: '🗑️', label: 'Wastebasket' },
    { emoji: '📦', label: 'Package' },
    { emoji: '📫', label: 'Mailbox' },
    { emoji: '📬', label: 'Open Mailbox' },
    { emoji: '📭', label: 'Empty Mailbox' },
    { emoji: '📮', label: 'Postbox' },
    { emoji: '📣', label: 'Megaphone' },
    { emoji: '🔔', label: 'Bell' },
    { emoji: '🔕', label: 'Bell Slash' },
    { emoji: '🎁', label: 'Gift' },
    { emoji: '🎀', label: 'Ribbon' },
    { emoji: '🎊', label: 'Confetti Ball' },
    { emoji: '🎉', label: 'Party Popper' },
    { emoji: '🪩', label: 'Mirror Ball' },
    { emoji: '🛒', label: 'Shopping Cart' },
    { emoji: '💈', label: 'Barber Pole' },
    { emoji: '🪥', label: 'Toothbrush' },
    { emoji: '🧴', label: 'Lotion Bottle' },
    { emoji: '🧷', label: 'Safety Pin' },
    { emoji: '🪡', label: 'Spool of Thread' },
    { emoji: '🧵', label: 'Thread' },
    { emoji: '🧶', label: 'Yarn' },
    { emoji: '🧰', label: 'Toolbox' },
    { emoji: '🔧', label: 'Wrench' },
    { emoji: '🔨', label: 'Hammer' },
    { emoji: '⚙️', label: 'Gear' },
    { emoji: '⛓️', label: 'Chains' },
    { emoji: '🪝', label: 'Hook' },
    { emoji: '🏺', label: 'Amphora' },
    { emoji: '🪬', label: 'Hamsa' },
    { emoji: '🧿', label: 'Nazar Amulet' },
    { emoji: '💎', label: 'Diamond' },
    { emoji: '👑', label: 'Crown' },
    { emoji: '💍', label: 'Ring' },
    { emoji: '💄', label: 'Lipstick' },
    { emoji: '👓', label: 'Glasses' },
    { emoji: '🕶️', label: 'Sunglasses' },
    { emoji: '🪖', label: 'Helmet' },
    { emoji: '👒', label: 'Hat' },
    { emoji: '🎩', label: 'Top Hat' },
    { emoji: '🪭', label: 'Folding Hand Fan' },
    { emoji: '💼', label: 'Briefcase' },
    { emoji: '🎒', label: 'Backpack' },
    { emoji: '👜', label: 'Handbag' },
    { emoji: '👛', label: 'Purse' },
    { emoji: '💰', label: 'Money Bag' },
    { emoji: '💸', label: 'Money Wings' },
    { emoji: '💳', label: 'Credit Card' },
    { emoji: '🏧', label: 'ATM' },
  ],

  Symbols: [
    { emoji: '❤️', label: 'Red Heart' },
    { emoji: '🧡', label: 'Orange Heart' },
    { emoji: '💛', label: 'Yellow Heart' },
    { emoji: '💚', label: 'Green Heart' },
    { emoji: '💙', label: 'Blue Heart' },
    { emoji: '💜', label: 'Purple Heart' },
    { emoji: '🖤', label: 'Black Heart' },
    { emoji: '🤍', label: 'White Heart' },
    { emoji: '🤎', label: 'Brown Heart' },
    { emoji: '💔', label: 'Broken Heart' },
    { emoji: '❣️', label: 'Heart Exclamation' },
    { emoji: '💕', label: 'Two Hearts' },
    { emoji: '💞', label: 'Revolving Hearts' },
    { emoji: '💓', label: 'Beating Heart' },
    { emoji: '💗', label: 'Growing Heart' },
    { emoji: '💖', label: 'Sparkling Heart' },
    { emoji: '💘', label: 'Heart Arrow' },
    { emoji: '💝', label: 'Heart Ribbon' },
    { emoji: '💟', label: 'Heart Decoration' },
    { emoji: '♾️', label: 'Infinity' },
    { emoji: '✅', label: 'Check Mark' },
    { emoji: '❌', label: 'Cross Mark' },
    { emoji: '⭕', label: 'Circle' },
    { emoji: '🔴', label: 'Red Circle' },
    { emoji: '🟠', label: 'Orange Circle' },
    { emoji: '🟡', label: 'Yellow Circle' },
    { emoji: '🟢', label: 'Green Circle' },
    { emoji: '🔵', label: 'Blue Circle' },
    { emoji: '🟣', label: 'Purple Circle' },
    { emoji: '⚫', label: 'Black Circle' },
    { emoji: '⚪', label: 'White Circle' },
    { emoji: '🟤', label: 'Brown Circle' },
    { emoji: '🔶', label: 'Orange Diamond' },
    { emoji: '🔷', label: 'Blue Diamond' },
    { emoji: '🔸', label: 'Small Orange Diamond' },
    { emoji: '🔹', label: 'Small Blue Diamond' },
    { emoji: '🔺', label: 'Red Triangle Up' },
    { emoji: '🔻', label: 'Red Triangle Down' },
    { emoji: '🔲', label: 'Black Square Button' },
    { emoji: '🔳', label: 'White Square Button' },
    { emoji: '▪️', label: 'Black Small Square' },
    { emoji: '▫️', label: 'White Small Square' },
    { emoji: '◾', label: 'Black Medium-Small Square' },
    { emoji: '◽', label: 'White Medium-Small Square' },
    { emoji: '◼️', label: 'Black Medium Square' },
    { emoji: '◻️', label: 'White Medium Square' },
    { emoji: '⬛', label: 'Black Large Square' },
    { emoji: '⬜', label: 'White Large Square' },
    { emoji: '🔊', label: 'Speaker' },
    { emoji: '🔇', label: 'Muted Speaker' },
    { emoji: '🔈', label: 'Low Volume' },
    { emoji: '🔉', label: 'Medium Volume' },
    { emoji: '🔔', label: 'Bell' },
    { emoji: '🔕', label: 'Bell Slash' },
    { emoji: '📣', label: 'Megaphone 2' },
    { emoji: '📢', label: 'Loudspeaker' },
    { emoji: '🔀', label: 'Shuffle' },
    { emoji: '🔁', label: 'Repeat' },
    { emoji: '🔂', label: 'Repeat One' },
    { emoji: '▶️', label: 'Play' },
    { emoji: '⏩', label: 'Fast Forward' },
    { emoji: '⏭️', label: 'Next Track' },
    { emoji: '⏯️', label: 'Play Pause' },
    { emoji: '◀️', label: 'Reverse' },
    { emoji: '⏪', label: 'Rewind' },
    { emoji: '⏮️', label: 'Previous Track' },
    { emoji: '⏫', label: 'Up Arrow' },
    { emoji: '⏬', label: 'Down Arrow' },
    { emoji: '⏸️', label: 'Pause' },
    { emoji: '⏹️', label: 'Stop' },
    { emoji: '⏺️', label: 'Record' },
    { emoji: '⁉️', label: 'Exclamation Question' },
    { emoji: '‼️', label: 'Double Exclamation' },
    { emoji: '❓', label: 'Question Mark' },
    { emoji: '❗', label: 'Exclamation Mark' },
    { emoji: '💯', label: '100' },
    { emoji: '🔥', label: 'Fire' },
    { emoji: '💫', label: 'Dizzy' },
    { emoji: '⭐', label: 'Star 2' },
    { emoji: '🌟', label: 'Glowing Star 2' },
    { emoji: '✨', label: 'Sparkles 2' },
    { emoji: '💥', label: 'Collision' },
    { emoji: '💦', label: 'Sweat Droplets' },
    { emoji: '💨', label: 'Dashing Away' },
    { emoji: '🕳️', label: 'Hole' },
    { emoji: '💬', label: 'Speech Bubble' },
    { emoji: '💭', label: 'Thought Bubble' },
    { emoji: '🗯️', label: 'Anger Bubble' },
    { emoji: '💤', label: 'Zzz' },
    { emoji: '🚫', label: 'Prohibited' },
    { emoji: '⛔', label: 'No Entry' },
    { emoji: '📵', label: 'No Mobile Phones' },
    { emoji: '🔞', label: 'No Under 18' },
    { emoji: '☢️', label: 'Radioactive' },
    { emoji: '☣️', label: 'Biohazard' },
    { emoji: '⚠️', label: 'Warning' },
    { emoji: '♻️', label: 'Recycling' },
    { emoji: '✔️', label: 'Check Mark 2' },
    { emoji: '🆕', label: 'New Button' },
    { emoji: '🆙', label: 'Up Button' },
    { emoji: '🆒', label: 'Cool Button' },
    { emoji: '🆓', label: 'Free Button' },
    { emoji: '🆖', label: 'NG Button' },
    { emoji: '🆗', label: 'OK Button' },
    { emoji: '🆘', label: 'SOS Button' },
    { emoji: '🆚', label: 'VS Button' },
  ],
};
